UserParameter=wavelog.active_users[*],mysql -u $1 -p'$2' -NB -e "SELECT COUNT(*) FROM users WHERE TIMESTAMPDIFF(MINUTE, last_seen, UTC_TIMESTAMP()) < $4;" $3
UserParameter=wavelog.total_qsos[*],mysql -u $1 -p'$2' -NB -e "SELECT count(COL_PRIMARY_KEY) FROM $4;" $3
UserParameter=wavelog.total_users[*],mysql -u $1 -p'$2' -NB -e "SELECT count(user_id) FROM users WHERE clubstation=0;" $3
UserParameter=wavelog.mig_version[*],mysql -u $1 -p'$2' -NB -e "SELECT version FROM migrations;" $3
UserParameter=wavelog.app_version[*],mysql -u $1 -p'$2' -NB -e "SELECT option_value FROM options WHERE option_name = 'version';" $3
UserParameter=wavelog.avail_version[*],mysql -u $1 -p'$2' -NB -e "SELECT option_value FROM options WHERE option_name = 'latest_release';" $3
UserParameter=wavelog.total_locations[*],mysql -u $1 -p'$2' -NB -e "SELECT count(station_id) FROM station_profile;" $3
UserParameter=wavelog.total_logbooks[*],mysql -u $1 -p'$2' -NB -e "SELECT count(logbook_id) FROM station_logbooks;" $3
UserParameter=wavelog.total_clubstations[*],mysql -u $1 -p'$2' -NB -e "SELECT count(user_id) FROM users WHERE clubstation=1;" $3
